hmcts/azure-devops-templates

templates/common/common.yml

New task to install .net core sdk

New task in common template for installing .net core SDK

---

jobs/aadAppRegistration.yml

New step to validate parameters. This step will check if deployment is performed form master branch and will fail the build if deployment is targeting production like environments like "aat", "pilot", "prod" from a feature branch.
**Failed:**
**Successful:**

Variable validation

---

README.md
jobs/aadAppRegistration.yml

No logical change just updates the logging:

Updated spelling of replay to reply

---

templates/azureResourceGroupDeployment/azureResourceGroupDeploymentVhWebsite.yml

Updated the condition so that the step is skipped if previous steps have failed.

New condition to skip the steps if previous steps have failed

---

templates/publishArtifacts/publishArtifacts.yml

Adding a condition to skip step that would package Infrastructure code if Infrastructure code is not in the applications source code repository.
From:
To:

Infrastructure condition

---

templates/common/common.yml

add missing semi colon to fix broken template
```
[ ] Yes
[ x] No
```

add missing semicolon

---

templates/npm/npm.yml

add linting step

---

jobs/aadAppRegistration.yml

https://tools.hmcts.net/jira/browse/RDO-3526
A new step to set group membership claims if needed while provisioning AAD app.
```
[ ] Yes
[x ] No
```

New step to set group membership claims for the AAD app 

---

jobs/angularDotNetCore.yml
templates/publishArtifacts/publishArtifacts.yml

n/a
exposes the dal project so that the preview environment can be cleared down between PR builds
```
[ ] Yes
[x] No
```

Expose dal artifact

---

jobs/angularDotNetCore.yml
templates/getSecrets/getSecrets.yml

None.
Modified condition for reading key vault secrets to check the parameter instead of the variable from the template.
**Does this PR introduce a breaking change?**
Nope. It even makes stuff better :)

put in a different conditional for when to get the keyvault

---

jobs/aadAppRegistration.yml

https://tools.hmcts.net/jira/browse/RDO-3679
New step that will add "Grant permissions" functionality through provisioning pipeline.
This PR depends on [PR ](https://github.com/hmcts/vh-ps-modules/pull/17)
Before merging comment out lines 67 and 68 as they make the pipeline to checkout PS modules from feature branch.
```
[ ] Yes
[x] No
```

Grant permissions aad rdo 3679

---

jobs/aadAppRegistration.yml

n/a
Adding new environments that can be used for provisioning AAD apps.
```
[ ] Yes
[ x] No
```

Adding new environments

---

templates/azureResourceGroupDeployment/azureResourceGroupDeploymentVhWebsite.yml

n/a
Adding new environments to conditions that handle Az subscription selection.
```
[ ] Yes
[ x] No
```

Added new envirionmesnt to the condition

---

jobs/aadAppRegistration.yml

n/a
Adding missing environments to credential selector.
```
[ ] Yes
[ x] No
```

New environments to comparison operator

---

templates/getSecrets/getSecrets.yml
templates/npm/npm.yml

n/a
The extra rules in the condition will make sure to run the steps only if the previous step has been successful. This will speed up the build to fail faster if there are errors in the build steps. 
```
[ ] Yes
[x ] No
```

Additional rules in the condition

---

templates/getSecrets/getSecrets.yml

n/a
Fixing a condition that was causing the build to fail.
```
[ ] Yes
[x ] No
```

Fixed condition

---

templates/getSecrets/getSecrets.yml

n/a
fixing indenation
```
[ ] Yes
[x ] No
```

Fixing indentation

---

package-lock.json

https://tools.hmcts.net/jira/browse/RDO-4406
```
[ ] Yes
[x ] No
```

Updated package versions

---

jobs/angularDotNetCore.yml
templates/npm/npm.yml

n/a
Allow build pipeline to define node version. Falls back to latest previous version.
```
[ ] Yes
[X] No
```

Added in default node version to job

---

jobs/aadAppRegistration.yml
templates/azureResourceGroupDeployment/azureResourceGroupDeploymentVhWebsite.yml

n/a
Adding support for CORS settings
```
[ ] Yes
[x ] No
```

Adding support for CORS settings

---

jobs/efMigration.yml

https://tools.hmcts.net/jira/browse/VIH-5109
ADDED:
new efmigration.yml job template to generate db migration scripts and publish them as build artifacts
```
[ ] Yes
[X] No
```

new pipelines to generate ef db migration scripts

---

stages/dotnet-package.yml
stages/dotnet-release.yml
templates/vh-release.yml

Support CD via yml pipelines
```
[ ] Yes
[X] No
```

Support CD via yml pipelines

---

templates/vh-release.yml

move condition out of foreach and fix use of parameters in condition
```
[ ] Yes
[X] No
```

fix condition

---

jobs/azWebAppDeployJob.yml
stages/dotnet-package.yml
stages/dotnet-release.yml
stages/dotnet-test.yml
stages/node-test.yml
templates/tests/stryker.yml

Add support for node/web app jobs
```
[ ] Yes
[x] No
```

Add support for node/web app jobs

---

templates/vh-release.yml

provide option to assign variable group based on current env
```
[ ] Yes
[x] No
```

Enabled Dynamic Variables Assignment Based On Env

---

jobs/azWebAppDeployJob.yml
jobs/multiDeviceTest.yml
jobs/secretGathering.yml
stages/dotnet-release.yml

Add support for multi device testing
```
[ ] Yes
[x] No
```

Add Support for multi device testing

---

jobs/azWebAppDeployJob.yml
stages/dotnet-package.yml
stages/dotnet-test.yml
templates/vsBuild/dotnetBuild.yml
templates/vsBuild/vsBuild.yml

VIH-6716
Support nuget config for projects with third-party feeds
```
[ ] Yes
[x] No
```

VIH-6716 support nuget config

---

stages/dotnet-package.yml

Use gitversion config for nuget stage

---

stages/dotnet-package.yml

VIH-6688
```
[ ] Yes
[X] No
```

VIH-6688 - no restore on publish, already done in previous step (unless cached)

---

stages/dotnet-package.yml

VIH-6688 
```
[ ] Yes
[X] No
```

VIH-6688 notification publish fix

---

stages/dotnet-package.yml

VIH-6688
```
[ ] Yes
[X] No
```

VIH-6688 added variable for debugging

---

stages/dotnet-package.yml

VIH-6688
```
[ ] Yes
[X] No
```

VIH-6688 duplicated tasks with conditions

---

jobs/secretGathering.yml

fixing firewall whitelisting issue

---

jobs/aadAppRegistration.yml
templates/vh-release.yml

- Added Test3 Env
```
[ ] Yes
[X] No
```

VIH-5552 Added Test3 Env

---

jobs/azWebAppDeployJob.yml
jobs/multiDeviceTest.yml
jobs/secretGathering.yml

adding loop to ensure azdo agent gets it public ip address

---

templates/vh-release.yml

VIH-7130 
auto-deploy to sandbox when builds are triggered from merge to master
```
[ ] Yes
[x] No
```

VIH-7130 auto deploy to sandbox 

---

jobs/azWebAppDeployJob.yml
stages/dotnet-test.yml

- remove the secrets logging to the pipelines
```
[ ] Yes
[x] No
```

Azdo logging remediation

---

lint_config_file
package.json

N/A
beacuse yaml-lint is crap
```
[ ] Yes
[X] No
```

changed linter from yaml-lint to yamllint

---

jobs/azWebAppDeployJob.yml

N/A
added conditional around staging app settings slot to ensure settings are for the staging slot
```
[ ] Yes
[X] No
```

Fix for vh video

---

jobs/azWebAppDeployJob.yml

- Check when the deploying slot is production remove slot option the azure cli command
```
[ ] Yes
[x] No
```

Fix when deploy to directly to production slot

---

jobs/azWebAppDeployJob.yml

- IsLive appsetting user api is set to false during smoke test run for admin web in prod.
```
[ ] Yes
[x] No
```

IsLive appsetting user api is set to false during smoke test run for admin web in prod

---

jobs/azWebAppDeployJob.yml

- fix typo
```
[ ] Yes
[x] No
```

Islive task automated

---

jobs/azWebAppDeployJob.yml

https://tools.hmcts.net/jira/browse/VIH-6831
This will automate the vanity url step during releases to the upper envs
Please do not merge after approval as the web apps also need updating
```
[ ] Yes -> 
[X] No
```

Vih 6831 automate vanity urls

---

jobs/azWebAppDeployJob.yml

Swapped the position of appsettings values update and deploying app to app service.
- disabled the smoke tests in prod env
```
[X] Yes
[ ] No
```

swapped the app settings and disabled smoke tests

---

jobs/secretGathering.yml

N/A
Extra checks on agent IP
```
[ ] Yes
[X] No
```

extra logging for FW rules on KV

---

templates/tests/Azure/LoadBalancer/healthprobe.yml
templates/tests/Azure/VirtualMachine/validSslCertificate.yml

Added two new templates for testing Azure Infra including Load Balancer Health Probe and VM SSL Certificates.
```
[ ] Yes
[ X ] No
```

Azure LB and VM tests

---

templates/keyvault/pruneNetworkRules.yaml

Add template to delete all ip rules in KV Networking

VIH-7725 Add KV Network rule prune

---

templates/common/pipeline-details.yml

This has been build to get the Schedule Name from the Azure DevOps REST API Get Build.
Instead of a single purpose task, this allows you to request any property from the API request and so can be reused for any request.
```
[ ] Yes
[ X ] No
```

Get Build details from API

---

templates/common/pipeline-details.yml
templates/keyvault/pruneNetworkRules.yaml

fix url issues

---

azure-pipelines.yml

VIH-8065
Updating to latest Ubuntu vm
```
[ ] Yes
[x ] No
```

VIH-8065-Updated yml to latest Ubuntu vm

---

jobs/azWebAppDeployJob.yml
templates/vh-release.yml

VIH-7961
Added some logic to allow toggling of the Smoke Tests 
```
[ ] Yes
[X] No
```

VIH-7961 remove smoke check

---

templates/common/get-variable-group.yml
templates/keyvault/copyCertificate.yml

Get a Variable Group from Azure DevOps and put json content into variable
Get Certificate from one KV Instance and copy into another KV Instance
```
[ ] Yes
[ X ] No
```

Get Variable Group JSON and Copy Az Kv Certs

---

templates/common/get-variable-group.yml

Fix some issues with the group tasks after using them.
```
[ ] Yes
[ X ] No
```

Get AzDO Group Fixes

---

templates/vh-release.yml

N/A
changed refs from test3 to test2
```
[ ] Yes
[X] No
```

changed refs from test3 to test2

---

templates/ApiManagement/check-soft-deleted.yaml
templates/ApiManagement/purge.yaml

https://tools.hmcts.net/jira/browse/VIH-7898
Add task to purge APIM
Add task to check if APIM name is available 
```
[ ] Yes
[ X ] No
```

VIH-7898 Add APIM Purging and Name checking

---

jobs/azWebAppDeployJob.yml
jobs/multiDeviceTest.yml
templates/Azure/WebApps/removeFirewallException.yml

Check if rule for access in web app exists before trying to delete it
```
[ ] Yes
[ X ] No
```

update scripts to check if the acces exists first

---

jobs/azWebAppDeployJob.yml

N/A
deploy step for staging slot duplicated, no idea why. Removed.
```
[ ] Yes
[X] No
```

removed extra deployment task

---

jobs/azWebAppDeployJob.yml
templates/Azure/WebApps/removeFirewallException.yml

N/A
fix of new firewall template for video-web, az cli for webapps apparently does not take production as a valid arg to --slotName
```
[ ] Yes
[ ] No
```

Video web fw fix

---

jobs/azWebAppDeployJob.yml

N/A
Quoted uri's for prod/preprod
```
[ ] Yes
[X] No
```

quoted vanity urls to avoid escape chars

---

templates/Azure/Common/unlock-resource.yml

Add task to unlock resources
```
[ ] Yes
[ X ] No
```

Add unlock resource task

---

azure-pipelines.yml
jobs/aadAppRegistration.yml
jobs/azWebAppDeployJob.yml
jobs/multiDeviceTest.yml
jobs/secretGathering.yml
stages/dotnet-ac.yml
stages/dotnet-package.yml
stages/dotnet-release.yml
stages/dotnet-test.yml
stages/node-test.yml
templates/common/common.yml

https://tools.hmcts.net/jira/browse/VIH-8096
- changed ubuntu version to always use the latest
- changed the gitversion tasks
```
[ ] Yes
[x] No
```

VIH-8096 update ubuntu version spec

---

jobs/azWebAppDeployJob.yml

N/A
Ensuring Vanity url switch is triggered for Video-Web which is deployed directly to the production slot. 
```
[ ] Yes
[X] No
```

Vanity url video web

---

templates/Azure/Postgres/firewall.yaml

Add template to whitelist IP addresses on the PostgresSQL Firewall
```
[ ] Yes
[ X ] No
```

PostgresSQL Firewall whitelisting

---

templates/Azure/NetworkSecurityGroup/add.yml
templates/Azure/NetworkSecurityGroup/remove.yaml
templates/tests/ffmpeg.yml

Add FFMPEG testing template
Add NSG add and remove templates
```
[ ] Yes
[ X ] No
```

VIH-8475 Add FFMPEG Template

---

templates/tests/ssl-check.yaml

Add a SSL checker from SSL Labs
```
[ ] Yes
[ X ] No
```

VIH-8509 add ssl check

---

templates/Azure/LogicApp/send-pipeline-alert.yaml

Fix syntax error when using the logic app template
```
[ ] Yes
[ X ] No
```

fix logic app

---

templates/Azure/Certificates/Request.yaml
templates/Azure/Certificates/purge.yaml

https://tools.hmcts.net/jira/browse/VIH-8530
Add cert rotation
Add cert purge
```
[ ] Yes
[ x ] No
```

VIH-8530 - Add Cert requesting

---

jobs/azWebAppDeployJob.yml

https://tools.hmcts.net/jira/browse/VIH-8563
Added some error outputs, a try/catch around adding the firewall rules and reduced the sleep timer.
99.9% certain this doesn't need to be merged into main as the error is with the sandbox access to the kinley healthcheck.
```
[ ] Yes
[X ] No
```

Vih 8563 network addition for smoke test

---

templates/Azure/ApiManagement/update-apim-api.yaml

This task will update an existing API by importing the json url
```
[ ] Yes
[ X ] No
```

HMIS-961 Add APIM API update

---

templates/Azure/Vm/install.yaml

https://tools.hmcts.net/jira/browse/VIH-8527
Added az vm extension wait command to attempt to make sure extension installs.
```
[ ] Yes
[x] No
```

VIH-8527 Added extension wait command to install.yaml

---

templates/Azure/Certificates/Request.yaml

Allow production certs to be generated in Staging
```
[ ] Yes
[ X ] No
```

Allow prod certs on stg

---

templates/Azure/Certificates/Request.yaml

[VIH-8530](https://tools.hmcts.net/jira/browse/VIH-8530)
Use the Full PFX Chain instead of standard cert
```
[ ] Yes
[ X ] No
```

VIH-8530 - Update to use full PFX chain

---

templates/Azure/Certificates/Request.yaml

VIH-8530 
Due to Pexip we need to have a chain without the root cert.
Therefore we are going to merge the outputted cert, intermediate and key files to package
```
[ ] Yes
[ X ] No
```

VIH-8530 - Repackage cert, inter, key certs

---

templates/tests/terraform/security.yaml

No Ticket
changed publishRunAttachatments in security.yml to publishRunAttachments 
```
[ ] Yes
[ x] No
```

Quick fix for publishRunAttachments

---

stages/dotnet-package.yml

VIH-8651 install specific node version

---

stages/dotnet-package.yml
stages/dotnet-test.yml

VIH-8651install specific nbode version in test stage

---

stages/dotnet-package.yml
stages/dotnet-test.yml

VIH-8651 specifu node version

---

templates/Containerisation/helm/helm-push.yaml

update with correct commands
```
[ ] Yes
[ X ] No
```

Correct helm commands

---

templates/Containerisation/helm/helm-push-v2-max.yaml
templates/Containerisation/helm/helm-push.yaml

Update the API Version 2 script for helm
```
[ ] Yes
[ X ] No
```

Helm fix version for api 2

---

templates/Azure/Vm/install-ext-by-api.yaml

template file added to install linux extensions via REST api
```
[ ] Yes
[ X] No
```

template for installing linux osi via rest api

---

templates/Azure/Vm/install-ext-by-api.yaml

template update for installing linux osi via rest api
```
[ ] Yes
[ X] No
```

template update for installing linux osi via rest api

---

templates/Containerisation/helm/push-to-helm-chart-repo.yaml
templates/Github/get-app-token.yaml
templates/Github/get-installation-token.yaml
templates/Github/get-jwt.yaml
templates/Github/push-to-helm-chart-repo.yaml

https://tools.hmcts.net/jira/browse/VIH-8767
Templates to get JWT, Installation token and push charts to helm chart repo
```
[ ] Yes
[ X ] No
```

Helm chart push

---

templates/Azure/Aks/get-load-balancer.yaml
templates/Azure/Dns/private-dns-add-aks-pr.yaml
templates/Azure/Dns/private-dns-add.yaml
templates/Azure/Dns/private-dns-remove.yaml
templates/Containerisation/helm/helm-deploy.yaml

https://tools.hmcts.net/jira/browse/VIH-8769
Add Private DNS to AKS
```
[ ] Yes
[ X ] No
```

Private dns

---

templates/Containerisation/helm/helm-deploy.yaml
templates/Github/bump-chart-versions.yaml
templates/Github/clone.yaml
templates/Github/get-pull-request-details.yaml

https://tools.hmcts.net/jira/browse/VIH-8809
- Bump Chart versions
- Get PR details
- Checkout repos
- helm deploy updates
```
[ ] Yes
[ X ] No
```

VIH-8809 - Add new GitHub tasks

---

templates/Azure/AAD/apps/add-remove-replyruls--no-sc.yaml
templates/Azure/AAD/apps/add-remove-replyruls.yaml
templates/Azure/AAD/apps/get-by-name--no-sc.yaml
templates/Azure/AAD/apps/get-by-name.yaml

https://tools.hmcts.net/jira/browse/VIH-8831
Tasks to add and remove the AD App reply URLs
```
[ ] Yes
[ X ] No
```

VIH-8831 Add/Remove AD App ReplyUrls

---

templates/Azure/Vm/start-stop-vm.yaml

https://tools.hmcts.net/jira/browse/VIH-8544
Azdo piplein template to start/stop vms 
```
[ ] Yes
[X] No
```

start-stop-vm

---

jobs/msSqlDatabaseDeployJob.yml
jobs/secretGathering.yml
stages/dotnet-package.yml
stages/dotnet-release.yml
templates/Azure/KeyVault/firewall-exception-add.yaml
templates/Azure/KeyVault/firewall-exception-remove.yaml
templates/Azure/KeyVault/get-secret.yaml
templates/Database/EntityFramework/deploy-ms-sql.yaml
templates/Database/EntityFramework/generate-script.yaml
templates/Database/MsSql/split-connection-string.yaml
templates/vh-release.yml

https://tools.hmcts.net/jira/browse/VIH-8887
Add the EF Migration download task
Add the EF Deployment task
Add release to pipeline
```
[ ] Yes
[ X ] No
```

VIH-8887 EF Deployment tasks and VH pipeline

---

templates/Azure/Dns/private-dns-remove.yaml

N/A
split the sub name (which is used for the SC) from the dns sub name (used to locate the private dns zone) 
changed resourceGroup param to dnsResourceGroup for readiblity 
```
[X] Yes
[] No
```

added a new dnssub and dns rg param

---

pipelines/azure-pipelines.remove-pod.yml
templates/Containerisation/helm/helm-remove.yaml

n/a
Reverting suffix to imageTag for readability
```
[ ] Yes
[X] No
```

reverted changes

---

stages/dotnet-package.yml

https://tools.hmcts.net/jira/browse/VIH-8887
downgrading the .net version used for building
```
[X] Yes
[ ] No
```

downgraded the .net version used for building

---

stages/dotnet-release.yml

If the VH DB Deployment job is running then we should make it a dependency for the Tests run
```
[ ] Yes
[ x ] No
```

VH Add reliance on db job in testing job if running

---

templates/tests/terraform/allTests.yaml
templates/tests/terraform/secrets.yaml

Remove the users path from code
```
[ ] Yes
[ x ] No
```

remove user path

---

templates/Azure/Common/get-service-connection-details.yaml
templates/Azure/Dns/private-dns-add.yaml
templates/Containerisation/docker/docker-compose.yaml
templates/Containerisation/docker/docker-push-azure.yaml
templates/Containerisation/helm/helm-deploy.yaml
templates/Containerisation/helm/helm-install.yaml
templates/Github/push-to-helm-chart-repo.yaml

- Fix Helm Deployments
- Fix spaces in script tasks
- add task to get context variables

Fixes for VH SDS templates

---

templates/Database/EntityFramework/run-entity-framework.yaml

[VIH-8958](https://tools.hmcts.net/jira/browse/VIH-8958)
add master template for entity framework
```
[ ] Yes
[ X ] No
```

VIH-8958 - Add Template to Run Entity Framework

---

jobs/azWebAppDeployJob.yml
templates/tests/terraform/security.yaml

Add logging to the VH setting powershell
Change the TF to fail if issues found.
```
[ ] Yes
[ x ] No
```

add logs and change failures

---

templates/Github/bump-chart-versions.yaml

VIH-9003
Bump the chart version if there is a change in the charts
```
[ ] Yes
[ x ] No
```

VIH-9003 - exit chart bump after bumped

---

templates/Containerisation/helm/helm-lint.yaml

VIH-9004
Add HELM Lint task
```
[ ] Yes
[ x ] No
```

VIH-9004 - helm lint task

---

templates/dotnet/publish-nuget-packages.yml

[VIH-9083](https://tools.hmcts.net/jira/browse/VIH-9083)
add template to add NuGet packages to azure artifacts.
```
[ ] Yes
[X ] No
```

VIH-9083 - Add Template to Publish NuGet Packages

---

jobs/azWebAppDeployJob.yml
templates/dotnet/publish-acceptance-tests.yml
templates/dotnet/replace-app-settings.yml
templates/dotnet/run-acceptance-tests.yml

VIH-8979
Add Acceptance Tests for VH
```
[ ] Yes
[ x ] No
```

VIH-8979 Add Acceptance Tests for VH

---

templates/dotnet/delete-nuget-package-versions-by-filter.yml
templates/dotnet/package-nuget-packages.yml
templates/dotnet/publish-nuget-packages.yml
templates/dotnet/push-nuget-packages.yml

VIH-9084
Add nuget tasks for packaging, pushing and deleting nuget packages
```
[ ] Yes
[ x ] No
```

VIH-9084 Add Nuget Pattern tasks

---

templates/dotnet/package-nuget-packages.yml

VIH-9084
Amend Task Display Names
```
[ ] Yes
[x ] No
```

VIH-9084 - Amend Display Names

---

templates/Database/EntityFramework/generate-script.yaml

N/A
VH - Add Publish Artifact Task
```
[ ] Yes
[ X ] No
```

VH - Add Publish Artifact Task

---

templates/dotnet/package-nuget-packages.yml

[VIH-9084](https://tools.hmcts.net/jira/browse/VIH-9084)
add tasks for Build.BuildNumber patch
```
[ ] Yes
[ X ] No
```

VIH9084 - Change Build Number

---

templates/Containerisation/docker/docker-push-azure.yaml

[VIH-8965](https://tools.hmcts.net/jira/browse/VIH-8965)
Add a task to reformat the tag if required.
```
[ ] Yes
[ x ] No
```

VIH-8965 - Add tag reformatting

---

templates/Containerisation/docker/docker-push-azure.yaml

Convert to PS Core
do loop of images within the scirpt to save on logins and task conflicts
print more messages
```
[ ] Yes
[ x ] No
```

Fix Docker Push Task

---

templates/Azure/Storage/break-lease.yaml

This task will break the lease on blob in storage
```
[ ] Yes
[ x ] No
```

Break lease on Blob task

---

templates/Azure/Vm/approve-terms.yaml

Approve a VM Image Terms
```
[ ] Yes
[ x ] No
```

VM Terms approval Task

---

templates/Github/push-to-helm-chart-repo.yaml

Amend push helm chart template
```
[ ] Yes
[x ] No
```

VIH-9999 - Amend push helm chart template

---

templates/Azure/Common/get-service-connection-details.yaml

Add Service Connection Flag
```
[ ] Yes
[ x ] No
```

Add Service Connection Flag

---

templates/Azure/AAD/apps/add-remove-replyruls--no-sc.yaml

VIH-9254
Fix the Redirect URL Script for AAD
```
[ ] Yes
[ x ] No
```

VIH-9254 - Fix the Redirect URL Script for AAD

---

templates/Dynatrace/credential-vault/add-username-password.yaml

VIH-9244
Dynatrace Credential Management
```
[ ] Yes
[ x ] No
```

VIH-9244 - Dynatrace Credential Management

---

templates/Containerisation/docker/docker-compose.yaml

https://tools.hmcts.net/jira/browse/VIH-9330
Add docker compose file as a parameter so that we can pass in a custom file name
Reference: https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/build/docker-compose?view=azure-devops
```
[ ] Yes
[x] No
```

VIH-9330 Add docker compose file as parameter

---

templates/dotnet/publish-acceptance-tests.yml
templates/dotnet/run-acceptance-tests.yml

VIH-9191
VIH-9191 -Amend Acceptance Tests
```
[ ] Yes
[x ] No
```

VIH-9191 -Amend Acceptance Tests

---

templates/dotnet/replace-app-settings.yml
templates/dotnet/run-acceptance-tests.yml

N/A
Remove appsettings.sds.json swap and allow the value swap code to deal with level 0 values
```
[ ] Yes
[ X] No
```

Vih 9999 remove json replace

---

templates/Containerisation/check-deployment.yaml
templates/Containerisation/docker/docker-push-azure.yaml

[VIH-9191](https://tools.hmcts.net/jira/browse/VIH-9191)
Adding a template step to allow the checking of a deployment into AKS
```
[ ] Yes
[X] No
```

VIH-9191 Add deployment check

---

templates/Containerisation/docker/docker-push-azure.yaml

VIH-9191
Output imagetag and add task name
```
[] Yes
[X] No
```

VIH-9191 Output imagetag and add task name

---

templates/Containerisation/check-deployment.yaml
templates/Containerisation/docker/docker-push-azure.yaml

VIH-9191
Fix docker push and check for clusters
```
[] Yes
[X] No
```

VIH-9191 Fix docker push and check for clusters

---

templates/Containerisation/docker/docker-push-azure.yaml

VIH-9999
Update date format of tag
```
[ ] Yes
[X] No
```

VIH-9999 Update date format of tag

---

azure-pipelines.yml
templates/dotnet/package-nuget-packages.yml
templates/dotnet/publish-acceptance-tests.yml

N/A
Updating the version of GITVersion to one that uses .net 6
```
[ ] Yes
[X] No
```

Upping GITVersion version

---

stages/node-test.yml

VIH-9418 - update agent version
```
[ ] Yes
[x ] No
```

VIH-9418 - update agent version

---

jobs/azWebAppDeployJob.yml

VIH-9999 - change agent to ubuntu 20.04
```
[ ] Yes
[x ] No
```

VIH-9999 - change agent to ubuntu 20.04

---

jobs/multiDeviceTest.yml
jobs/secretGathering.yml
stages/dotnet-ac.yml
stages/dotnet-package.yml
stages/dotnet-release.yml

VIH-9999 - change ubuntu version
VIH-9999 - change ubuntu version
```
[ ] Yes
[ x ] No
```

VIH-9999 - change ubuntu version

---

jobs/azWebAppDeployJob.yml
stages/dotnet-package.yml

VIH-9558 - Disable ZAP Tests Unless Specifying True 
VIH-9558 - Disable ZAP Tests Unless Specifying True 
```
[ ] Yes
[ x  ] No
```

VIH-9558 - Disable ZAP Tests Unless Specifying True 

---

templates/Azure/Monitor/link.ps1

adding expiresFater tag
```
[] Yes
[X] No
```

VIH-9999 Add expiresAfter

---

templates/Azure/Monitor/link.ps1
templates/Azure/Monitor/link.yaml

Adding expireAfter tag again
```
[ ] Yes
[X] No
```

VIH-9999 Add tags to dnslink

---

templates/tests/ffmpeg.yml

Add connection test to `ffmpeg` test
```
[ ] Yes
[X] No
```

VIH-9999 Add connection test to `ffmpeg` test

---

templates/Azure/Storage/networking-allow.yaml
templates/Azure/Storage/networking-deny.yaml
templates/Azure/Storage/networking-disabled.yaml

Adding some steps to set SA networking to `Allow`, `Deny` and `Disabled`
```
[ ] Yes
[X] No
```

VIH-9999 Adding steps for sa networking

---

templates/Database/EntityFramework/generate-script.yaml

VIH-9162 - Amend EF Scripts
VIH-9162 - Amend EF Scripts
```
[ ] Yes
[ x ] No
```

VIH-9162 - Amend EF Scripts

---

templates/Database/EntityFramework/generate-script.yaml

VIH-9162 - add NuGet authentication step
```
[ ] Yes
[ x ] No
```

VIH-9162 - add NuGet authentication step

---

stages/dotnet-tests/unit-and-integration-tests-container.yml

VIH-9699
Create a re-usable template for running tests with docker
```
[ ] Yes
[x] No
```

provide a template for testing inside containers

---

stages/dotnet-tests/unit-and-integration-tests-container.yml

VIH-9699
Provide the pull request id, branch and base to force sonar to detect the build as a PR
```
[ ] Yes
[x] No
```

VH tests container provide pr details

---

templates/dotnet/replace-app-settings.yml

VIH-0000 - FIX- force replace-app-settings.yml to check case of vars
```
[ ] Yes
[ x ] No
```

VIH-0000 - FIX- force replace-app-settings.yml to check case of vars

---

templates/dotnet/build-test-analyse.yml

VIH-9902 
add a dotnet restore step with sds nuget feed
```
[ ] Yes
[x] No
```

VIH-9902 add a dotnet restore step with sds nuget feed

---

templates/Database/EntityFramework/generate-script.yaml

Defaults the entity framework script to use .EF 6
```
[ ] Yes
[x] No
```

VIH-0000 Default ef script to dotnet 6

---

templates/dotnet/build-test-analyse.yml
templates/dotnet/package-nuget-packages.yml

N/A
Alow version in dotnet test
```
[ ] Yes
[ ] No
```

VIH-0000 Alow version in dotnet test

---

azure-pipelines.yml
templates/Azure/AAD/apps/add-remove-replyruls--no-sc.yaml

replyurl-change

---

templates/Azure/AAD/apps/add-remove-replyruls--no-sc.yaml

Update add-remove-replyruls--no-sc.yaml - Removed convert_to_json

---

stages/dotnet-tests/unit-and-integration-tests-container.yml
templates/Containerisation/docker/docker-compose.yaml

Fix docker compose - changing the Docker@1 to powershell scripts ADO task

---

templates/Containerisation/docker/docker-compose.yaml

Split the build and up command as they conflicting.

---

templates/Azure/Vm/install-ext-by-api.yaml

Fix extension - added show extension to exit the loop

---

stages/dotnet-tests/unit-and-integration-tests-container.yml
templates/sonarCloud/prepare.yml
templates/sonarCloud/runAnalysis.yml

N/A
Upgrade task version for PublishCodeCoverageResults and Sonar since V1 has been marked as obsolete for some time now

update task versions

---

templates/sonarCloud/prepare.yml
templates/sonarCloud/runAnalysis.yml

https://tools.hmcts.net/jira/browse/VIH-11083
Several pipeline tasks are warning as being deprecated. Updating the sonar cloud tasks to 3 would solve this deprecated issue.
```
[ ] Yes
[x ] No
```

VIH-11083 Update to SonarCloud 3

---

templates/Azure/Certificates/Request.yaml

https://tools.hmcts.net/jira/browse/VIH-11200
Enable pinning version of Posh-ACME PowerShell module
```
[ ] Yes
[x] No
```

VIH-11200 add posh-acme module version param

---

stages/dotnet-tests/unit-tests.yml

Update PublishCodeCoverageResults

update deprecated tasks

---

templates/dotnet/package-nuget-packages.yml

TBC
Re-order the get build number to run AFTER the gitversion task

Set fullsemver as build number

---

stages/dotnet-package.yml
stages/dotnet-test.yml
stages/node-test.yml
templates/common/common.yml
templates/dotnet/package-nuget-packages.yml
templates/dotnet/publish-acceptance-tests.yml
templates/dotnet/publish-nuget-packages.yml

VIH-11126
* update git version task to v3
* Still using VersionSpec 5, 6 has too many breaking changes and not clear how to safely update to get the same output

VIH-11126 update git version task to v3
